main: ch.hatbe2113.ObsidianLocationChanger.Main
name: ObsidianLocationChanger
author: hatbe2113
website: https://hatbe.ch
version: 2.0.0
api-version: 1.18
commands:
   home:
   sethome:
   delhome:
   homes:
